export default function Page() {
  return (
    <>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
      <div>dashboard</div>
    </>
  );
}
