// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivateSceneDescriptor } from "./ActivateSceneDescriptor";
import type { CustomActionDescriptor } from "./CustomActionDescriptor";
import type { CycleScenesDescriptor } from "./CycleScenesDescriptor";
import type { Device } from "./Device";
import type { DimDescriptor } from "./DimDescriptor";
import type { ForceTriggerRoutineDescriptor } from "./ForceTriggerRoutineDescriptor";
import type { UiActionDescriptor } from "./UiActionDescriptor";

export type Action = { "action": "ActivateScene" } & ActivateSceneDescriptor | { "action": "CycleScenes" } & CycleScenesDescriptor | { "action": "Custom" } & CustomActionDescriptor | { "action": "Dim" } & DimDescriptor | { "action": "ForceTriggerRoutine" } & ForceTriggerRoutineDescriptor | { "action": "SetDeviceState" } & Device | { "action": "Ui" } & UiActionDescriptor;
