// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capabilities = { 
/**
 * XY color space (0.0 - 1.0)
 */
xy: boolean, 
/**
 * Hue (0 - 360) and saturation (0.0 - 1.0)
 */
hs: boolean, 
/**
 * RGB values (0 - 255)
 */
rgb: boolean, 
/**
 * Color temperature (2000 - 6500)
 */
ct: { start: number, end: number, } | null, };
