// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from "./DeviceColor";

export type ControllableState = { power: boolean, 
/**
 * Current brightness, if supported
 */
brightness: number | null, 
/**
 * Current color, if supported
 */
color: DeviceColor | null, 
/**
 * Transition time in seconds
 */
transition: number | null, };
