// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivateSceneDescriptor } from "./ActivateSceneDescriptor";

export interface CycleScenesDescriptor { scenes: Array<ActivateSceneDescriptor>, nowrap: boolean | null, }
