// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to a device, always by id, serializes to `integration_id/device_id`
 */
export type DeviceKey = string;
