// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceIdRef } from "./DeviceIdRef";
import type { DeviceNameRef } from "./DeviceNameRef";

/**
 * A reference to a device, either by name or by id
 */
export type DeviceRef = DeviceIdRef | DeviceNameRef;
