// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllableDevice } from "./ControllableDevice";
import type { SensorDevice } from "./SensorDevice";

export type DeviceData = { "Controllable": ControllableDevice } | { "Sensor": SensorDevice };
