// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationId } from "./IntegrationId";

export type DeviceNameRef = { integration_id: IntegrationId, name: string, };
