// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimDescriptor } from "./DimDescriptor";
import type { DimDeviceLink } from "./DimDeviceLink";
import type { DimDeviceState } from "./DimDeviceState";

export type DimDeviceConfig = DimDeviceLink | DimDescriptor | DimDeviceState;
