// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DimDeviceState {
  power: boolean;
  color: String;
  brightness: number | null;
  transition_ms: bigint | null;
}
