// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { GroupId } from "./GroupId";

export type DimDescriptor = { 
/**
 * Optionally only apply dimming to these devices
 */
device_keys: Array<DeviceKey> | null, 
/**
 * Optionally only apply dimming to these groups
 */
group_keys: Array<GroupId> | null, step: number | null, };
