// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";

export type DimDeviceLink = { device_key: DeviceKey | null, name: string | null, brightness: number | null, };
