// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from "./DeviceColor";

export interface DimDeviceState { power: boolean, color: DeviceColor | null, brightness: number | null, transition_ms: number | null, }
