// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimDeviceConfig } from "./DimDeviceConfig";
import type { IntegrationId } from "./IntegrationId";

export type DimDevicesSearchConfig = Record<IntegrationId, Record<string, DimDeviceConfig>>;
