// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { SceneDeviceStates } from "./SceneDeviceStates";

export type FlattenedSceneConfig = { name: string, devices: SceneDeviceStates, active_overrides: Array<DeviceKey>, hidden: boolean | null, };
