// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";

export type FlattenedGroupConfig = { name: string, device_keys: Array<DeviceKey>, hidden: boolean | null, };
