// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimDeviceStates } from './DimDeviceStates';

export interface FlattenedDimConfig {
  name: string;
  devices: DimDeviceStates;
  hidden: boolean | null;
}
