// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutineId } from "./RoutineId";

export interface ForceTriggerRoutineDescriptor { routine_id: RoutineId, }
