// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutineId } from "./RoutineId";

export type ForceTriggerRoutineDescriptor = { routine_id: RoutineId, };
