// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManageKind = "Full" | { "Partial": { 
/**
 * Whether we have seen the device change state since the previously
 * issued command.
 */
prev_change_committed: boolean, } } | "Unmanaged" | "FullReadOnly" | "UnmanagedReadOnly";
