// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from "./DeviceColor";

export type SceneDeviceState = { power: boolean | null, color: DeviceColor | null, brightness: number | null, transition: number | null, };
