// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationId } from "./IntegrationId";
import type { SceneDeviceConfig } from "./SceneDeviceConfig";

/**
 * Device "search" config as used directly in the configuration file. We use device names instead of device id as key.
 */
export type SceneDevicesSearchConfig = { [key in IntegrationId]?: { [key in string]?: SceneDeviceConfig } };
