// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { IntegrationId } from "./IntegrationId";
import type { SceneDeviceConfig } from "./SceneDeviceConfig";

export interface SceneConfig { name: string, devices: Record | null, groups: Record | null, hidden: boolean | null, }