// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { SceneDeviceConfig } from "./SceneDeviceConfig";
import type { SceneDevicesSearchConfig } from "./SceneDevicesSearchConfig";
import type { SceneGroupsConfig } from "./SceneGroupsConfig";

export type SceneConfig = { name: string, devices: SceneDevicesSearchConfig | null, groups: SceneGroupsConfig | null, hidden: boolean | null, overrides: { [key in DeviceKey]?: SceneDeviceConfig } | null, };
