// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedDeviceState } from './ManagedDeviceState';

export type SensorDevice =
  | { value: boolean }
  | { value: string }
  | ManagedDeviceState;
