// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from './DeviceColor';

export type SensorDevice =
  | { value: boolean }
  | { value: string }
  | {
      color: DeviceColor | null;
      brightness: number | null;
      transition_ms: bigint | null;
    };
