// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllableState } from './ControllableState';

export type SensorDevice =
  | { value: boolean }
  | { value: string }
  | { value: number }
  | ControllableState;
