// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicesState } from "./DevicesState";
import type { FlattenedGroupConfig } from "./FlattenedGroupConfig";
import type { FlattenedSceneConfig } from "./FlattenedSceneConfig";
import type { GroupId } from "./GroupId";
import type { SceneId } from "./SceneId";

export interface StateUpdate { devices: DevicesState, scenes: Record, groups: Record, }