// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicesState } from "./DevicesState";
import type { FlattenedGroupsConfig } from "./FlattenedGroupsConfig";
import type { FlattenedScenesConfig } from "./FlattenedScenesConfig";
import type { JsonValue } from "./serde_json/JsonValue";

export type StateUpdate = { devices: DevicesState, scenes: FlattenedScenesConfig, groups: FlattenedGroupsConfig, ui_state: { [key in string]?: JsonValue }, };
